// Contract tests for api/app/queries/postcodes.ts.
// Snapshots are baked inline below — when we swap the Postgres backend for
// DuckDB (or anything else), these tests are the parity gate.
// Re-capture with `pnpm vitest run test/queries.postcodes.integration.ts -u`.

import { describe, expect, it } from "vitest";
import {
  find,
  findMany,
  nearestPostcodes,
  nearestPostcodesMany,
  random,
  search,
} from "../api/app/queries/postcodes";

// AB10 1AB is a live postcode in the seed (lat 57.14959, lng -2.096923).
const KNOWN_LIVE = "AB10 1AB";
const KNOWN_TERMINATED = "AB10 1AA";
const ANCHOR = { longitude: "-2.096923", latitude: "57.14959" };

describe("queries/postcodes (contract)", () => {
  describe("find()", () => {
    it("returns the row for a known live postcode", async () => {
      expect(await find(KNOWN_LIVE)).toMatchInlineSnapshot(`
        {
          "admin_county": null,
          "admin_county_id": null,
          "admin_district": "Aberdeen City",
          "admin_district_id": "S12000033",
          "admin_ward": "George St/Harbour",
          "admin_ward_id": "S13002842",
          "bua": null,
          "bua_id": null,
          "cancer_alliance": null,
          "cancer_alliance_id": null,
          "ccg": "Aberdeen City Community Health Partnership",
          "ccg_code": "012",
          "ccg_id": "S03000012",
          "ced": null,
          "ced_id": null,
          "constituency_id": "S14000061",
          "country": "Scotland",
          "date_of_introduction": "201106",
          "date_of_termination": null,
          "eastings": 394235,
          "european_electoral_region": "Scotland",
          "icb": null,
          "icb_id": null,
          "incode": "1AB",
          "index_of_multiple_deprivation": 3888,
          "latitude": 57.14959,
          "lep1": null,
          "lep1_id": null,
          "lep2": null,
          "lep2_id": null,
          "longitude": -2.096923,
          "lsoa": "George Street - 02",
          "lsoa11": "George Street - 02",
          "lsoa11_id": "S01006646",
          "lsoa21": "George Street - 02",
          "lsoa21_id": "S01013627",
          "lsoa_id": "S01013627",
          "msoa": "George Street",
          "msoa11": "George Street",
          "msoa11_id": "S02001261",
          "msoa21": "George Street",
          "msoa21_id": "S02002541",
          "msoa_id": "S02002541",
          "national_park": null,
          "national_park_id": null,
          "nhs_ha": "Grampian",
          "nhs_region": null,
          "nhs_region_id": null,
          "northings": 806529,
          "nuts": "Aberdeen City",
          "nuts_code": "TLM50",
          "nuts_id": "S30000026",
          "oa21_id": "S00136377",
          "outcode": "AB10",
          "parish": null,
          "parish_id": null,
          "parliamentary_constituency": "Aberdeen South",
          "pc_compact": "AB101AB",
          "pfa": "Scotland",
          "pfa_id": "S23000009",
          "postcode": "AB10 1AB",
          "primary_care_trust": "Aberdeen City Community Health Partnership",
          "quality": 1,
          "region": null,
          "ruc11": "(Scotland) Large Urban Area",
          "ruc11_id": "1",
          "ruc21": "Large Urban Areas",
          "ruc21_id": "1",
          "ttwa": "Aberdeen",
          "ttwa_id": "S22000047",
        }
      `);
    });
    it("returns null for a terminated postcode", async () => {
      expect(await find(KNOWN_TERMINATED)).toMatchInlineSnapshot(`null`);
    });
    it("normalises case and whitespace", async () => {
      expect(await find("  ab10 1ab  ")).toMatchInlineSnapshot(`
        {
          "admin_county": null,
          "admin_county_id": null,
          "admin_district": "Aberdeen City",
          "admin_district_id": "S12000033",
          "admin_ward": "George St/Harbour",
          "admin_ward_id": "S13002842",
          "bua": null,
          "bua_id": null,
          "cancer_alliance": null,
          "cancer_alliance_id": null,
          "ccg": "Aberdeen City Community Health Partnership",
          "ccg_code": "012",
          "ccg_id": "S03000012",
          "ced": null,
          "ced_id": null,
          "constituency_id": "S14000061",
          "country": "Scotland",
          "date_of_introduction": "201106",
          "date_of_termination": null,
          "eastings": 394235,
          "european_electoral_region": "Scotland",
          "icb": null,
          "icb_id": null,
          "incode": "1AB",
          "index_of_multiple_deprivation": 3888,
          "latitude": 57.14959,
          "lep1": null,
          "lep1_id": null,
          "lep2": null,
          "lep2_id": null,
          "longitude": -2.096923,
          "lsoa": "George Street - 02",
          "lsoa11": "George Street - 02",
          "lsoa11_id": "S01006646",
          "lsoa21": "George Street - 02",
          "lsoa21_id": "S01013627",
          "lsoa_id": "S01013627",
          "msoa": "George Street",
          "msoa11": "George Street",
          "msoa11_id": "S02001261",
          "msoa21": "George Street",
          "msoa21_id": "S02002541",
          "msoa_id": "S02002541",
          "national_park": null,
          "national_park_id": null,
          "nhs_ha": "Grampian",
          "nhs_region": null,
          "nhs_region_id": null,
          "northings": 806529,
          "nuts": "Aberdeen City",
          "nuts_code": "TLM50",
          "nuts_id": "S30000026",
          "oa21_id": "S00136377",
          "outcode": "AB10",
          "parish": null,
          "parish_id": null,
          "parliamentary_constituency": "Aberdeen South",
          "pc_compact": "AB101AB",
          "pfa": "Scotland",
          "pfa_id": "S23000009",
          "postcode": "AB10 1AB",
          "primary_care_trust": "Aberdeen City Community Health Partnership",
          "quality": 1,
          "region": null,
          "ruc11": "(Scotland) Large Urban Area",
          "ruc11_id": "1",
          "ruc21": "Large Urban Areas",
          "ruc21_id": "1",
          "ttwa": "Aberdeen",
          "ttwa_id": "S22000047",
        }
      `);
    });
    it("returns null for an invalid postcode", async () => {
      expect(await find("NOT A POSTCODE")).toMatchInlineSnapshot(`null`);
    });
    it("returns null for nullish input", async () => {
      expect(await find(null)).toMatchInlineSnapshot(`null`);
      expect(await find(undefined)).toMatchInlineSnapshot(`null`);
      expect(await find("")).toMatchInlineSnapshot(`null`);
    });
  });

  describe("findMany()", () => {
    it("returns rows for multiple compact postcodes", async () => {
      expect(await findMany(["AB101AB", "AB101AF"])).toMatchInlineSnapshot(`
        [
          {
            "admin_county": null,
            "admin_county_id": null,
            "admin_district": "Aberdeen City",
            "admin_district_id": "S12000033",
            "admin_ward": "George St/Harbour",
            "admin_ward_id": "S13002842",
            "bua": null,
            "bua_id": null,
            "cancer_alliance": null,
            "cancer_alliance_id": null,
            "ccg": "Aberdeen City Community Health Partnership",
            "ccg_code": "012",
            "ccg_id": "S03000012",
            "ced": null,
            "ced_id": null,
            "constituency_id": "S14000061",
            "country": "Scotland",
            "date_of_introduction": "199606",
            "date_of_termination": null,
            "eastings": 394235,
            "european_electoral_region": "Scotland",
            "icb": null,
            "icb_id": null,
            "incode": "1AF",
            "index_of_multiple_deprivation": 3888,
            "latitude": 57.14959,
            "lep1": null,
            "lep1_id": null,
            "lep2": null,
            "lep2_id": null,
            "longitude": -2.096923,
            "lsoa": "George Street - 02",
            "lsoa11": "George Street - 02",
            "lsoa11_id": "S01006646",
            "lsoa21": "George Street - 02",
            "lsoa21_id": "S01013627",
            "lsoa_id": "S01013627",
            "msoa": "George Street",
            "msoa11": "George Street",
            "msoa11_id": "S02001261",
            "msoa21": "George Street",
            "msoa21_id": "S02002541",
            "msoa_id": "S02002541",
            "national_park": null,
            "national_park_id": null,
            "nhs_ha": "Grampian",
            "nhs_region": null,
            "nhs_region_id": null,
            "northings": 806529,
            "nuts": "Aberdeen City",
            "nuts_code": "TLM50",
            "nuts_id": "S30000026",
            "oa21_id": "S00136377",
            "outcode": "AB10",
            "parish": null,
            "parish_id": null,
            "parliamentary_constituency": "Aberdeen South",
            "pc_compact": "AB101AF",
            "pfa": "Scotland",
            "pfa_id": "S23000009",
            "postcode": "AB10 1AF",
            "primary_care_trust": "Aberdeen City Community Health Partnership",
            "quality": 1,
            "region": null,
            "ruc11": "(Scotland) Large Urban Area",
            "ruc11_id": "1",
            "ruc21": "Large Urban Areas",
            "ruc21_id": "1",
            "ttwa": "Aberdeen",
            "ttwa_id": "S22000047",
          },
          {
            "admin_county": null,
            "admin_county_id": null,
            "admin_district": "Aberdeen City",
            "admin_district_id": "S12000033",
            "admin_ward": "George St/Harbour",
            "admin_ward_id": "S13002842",
            "bua": null,
            "bua_id": null,
            "cancer_alliance": null,
            "cancer_alliance_id": null,
            "ccg": "Aberdeen City Community Health Partnership",
            "ccg_code": "012",
            "ccg_id": "S03000012",
            "ced": null,
            "ced_id": null,
            "constituency_id": "S14000061",
            "country": "Scotland",
            "date_of_introduction": "201106",
            "date_of_termination": null,
            "eastings": 394235,
            "european_electoral_region": "Scotland",
            "icb": null,
            "icb_id": null,
            "incode": "1AB",
            "index_of_multiple_deprivation": 3888,
            "latitude": 57.14959,
            "lep1": null,
            "lep1_id": null,
            "lep2": null,
            "lep2_id": null,
            "longitude": -2.096923,
            "lsoa": "George Street - 02",
            "lsoa11": "George Street - 02",
            "lsoa11_id": "S01006646",
            "lsoa21": "George Street - 02",
            "lsoa21_id": "S01013627",
            "lsoa_id": "S01013627",
            "msoa": "George Street",
            "msoa11": "George Street",
            "msoa11_id": "S02001261",
            "msoa21": "George Street",
            "msoa21_id": "S02002541",
            "msoa_id": "S02002541",
            "national_park": null,
            "national_park_id": null,
            "nhs_ha": "Grampian",
            "nhs_region": null,
            "nhs_region_id": null,
            "northings": 806529,
            "nuts": "Aberdeen City",
            "nuts_code": "TLM50",
            "nuts_id": "S30000026",
            "oa21_id": "S00136377",
            "outcode": "AB10",
            "parish": null,
            "parish_id": null,
            "parliamentary_constituency": "Aberdeen South",
            "pc_compact": "AB101AB",
            "pfa": "Scotland",
            "pfa_id": "S23000009",
            "postcode": "AB10 1AB",
            "primary_care_trust": "Aberdeen City Community Health Partnership",
            "quality": 1,
            "region": null,
            "ruc11": "(Scotland) Large Urban Area",
            "ruc11_id": "1",
            "ruc21": "Large Urban Areas",
            "ruc21_id": "1",
            "ttwa": "Aberdeen",
            "ttwa_id": "S22000047",
          },
        ]
      `);
    });
    it("preserves DB row order regardless of input order", async () => {
      expect(await findMany(["AB101AF", "AB101AB"])).toMatchInlineSnapshot(`
        [
          {
            "admin_county": null,
            "admin_county_id": null,
            "admin_district": "Aberdeen City",
            "admin_district_id": "S12000033",
            "admin_ward": "George St/Harbour",
            "admin_ward_id": "S13002842",
            "bua": null,
            "bua_id": null,
            "cancer_alliance": null,
            "cancer_alliance_id": null,
            "ccg": "Aberdeen City Community Health Partnership",
            "ccg_code": "012",
            "ccg_id": "S03000012",
            "ced": null,
            "ced_id": null,
            "constituency_id": "S14000061",
            "country": "Scotland",
            "date_of_introduction": "199606",
            "date_of_termination": null,
            "eastings": 394235,
            "european_electoral_region": "Scotland",
            "icb": null,
            "icb_id": null,
            "incode": "1AF",
            "index_of_multiple_deprivation": 3888,
            "latitude": 57.14959,
            "lep1": null,
            "lep1_id": null,
            "lep2": null,
            "lep2_id": null,
            "longitude": -2.096923,
            "lsoa": "George Street - 02",
            "lsoa11": "George Street - 02",
            "lsoa11_id": "S01006646",
            "lsoa21": "George Street - 02",
            "lsoa21_id": "S01013627",
            "lsoa_id": "S01013627",
            "msoa": "George Street",
            "msoa11": "George Street",
            "msoa11_id": "S02001261",
            "msoa21": "George Street",
            "msoa21_id": "S02002541",
            "msoa_id": "S02002541",
            "national_park": null,
            "national_park_id": null,
            "nhs_ha": "Grampian",
            "nhs_region": null,
            "nhs_region_id": null,
            "northings": 806529,
            "nuts": "Aberdeen City",
            "nuts_code": "TLM50",
            "nuts_id": "S30000026",
            "oa21_id": "S00136377",
            "outcode": "AB10",
            "parish": null,
            "parish_id": null,
            "parliamentary_constituency": "Aberdeen South",
            "pc_compact": "AB101AF",
            "pfa": "Scotland",
            "pfa_id": "S23000009",
            "postcode": "AB10 1AF",
            "primary_care_trust": "Aberdeen City Community Health Partnership",
            "quality": 1,
            "region": null,
            "ruc11": "(Scotland) Large Urban Area",
            "ruc11_id": "1",
            "ruc21": "Large Urban Areas",
            "ruc21_id": "1",
            "ttwa": "Aberdeen",
            "ttwa_id": "S22000047",
          },
          {
            "admin_county": null,
            "admin_county_id": null,
            "admin_district": "Aberdeen City",
            "admin_district_id": "S12000033",
            "admin_ward": "George St/Harbour",
            "admin_ward_id": "S13002842",
            "bua": null,
            "bua_id": null,
            "cancer_alliance": null,
            "cancer_alliance_id": null,
            "ccg": "Aberdeen City Community Health Partnership",
            "ccg_code": "012",
            "ccg_id": "S03000012",
            "ced": null,
            "ced_id": null,
            "constituency_id": "S14000061",
            "country": "Scotland",
            "date_of_introduction": "201106",
            "date_of_termination": null,
            "eastings": 394235,
            "european_electoral_region": "Scotland",
            "icb": null,
            "icb_id": null,
            "incode": "1AB",
            "index_of_multiple_deprivation": 3888,
            "latitude": 57.14959,
            "lep1": null,
            "lep1_id": null,
            "lep2": null,
            "lep2_id": null,
            "longitude": -2.096923,
            "lsoa": "George Street - 02",
            "lsoa11": "George Street - 02",
            "lsoa11_id": "S01006646",
            "lsoa21": "George Street - 02",
            "lsoa21_id": "S01013627",
            "lsoa_id": "S01013627",
            "msoa": "George Street",
            "msoa11": "George Street",
            "msoa11_id": "S02001261",
            "msoa21": "George Street",
            "msoa21_id": "S02002541",
            "msoa_id": "S02002541",
            "national_park": null,
            "national_park_id": null,
            "nhs_ha": "Grampian",
            "nhs_region": null,
            "nhs_region_id": null,
            "northings": 806529,
            "nuts": "Aberdeen City",
            "nuts_code": "TLM50",
            "nuts_id": "S30000026",
            "oa21_id": "S00136377",
            "outcode": "AB10",
            "parish": null,
            "parish_id": null,
            "parliamentary_constituency": "Aberdeen South",
            "pc_compact": "AB101AB",
            "pfa": "Scotland",
            "pfa_id": "S23000009",
            "postcode": "AB10 1AB",
            "primary_care_trust": "Aberdeen City Community Health Partnership",
            "quality": 1,
            "region": null,
            "ruc11": "(Scotland) Large Urban Area",
            "ruc11_id": "1",
            "ruc21": "Large Urban Areas",
            "ruc21_id": "1",
            "ttwa": "Aberdeen",
            "ttwa_id": "S22000047",
          },
        ]
      `);
    });
    it("returns empty array for empty input", async () => {
      expect(await findMany([])).toMatchInlineSnapshot(`[]`);
    });
    it("returns empty array for all-unknown input", async () => {
      expect(await findMany(["ZZ999ZZ"])).toMatchInlineSnapshot(`[]`);
    });
  });

  describe("search()", () => {
    it("returns exact match when fully-specified postcode given", async () => {
      expect(await search({ postcode: KNOWN_LIVE })).toMatchInlineSnapshot(`
        [
          {
            "admin_county": null,
            "admin_county_id": null,
            "admin_district": "Aberdeen City",
            "admin_district_id": "S12000033",
            "admin_ward": "George St/Harbour",
            "admin_ward_id": "S13002842",
            "bua": null,
            "bua_id": null,
            "cancer_alliance": null,
            "cancer_alliance_id": null,
            "ccg": "Aberdeen City Community Health Partnership",
            "ccg_code": "012",
            "ccg_id": "S03000012",
            "ced": null,
            "ced_id": null,
            "constituency_id": "S14000061",
            "country": "Scotland",
            "date_of_introduction": "201106",
            "date_of_termination": null,
            "eastings": 394235,
            "european_electoral_region": "Scotland",
            "icb": null,
            "icb_id": null,
            "incode": "1AB",
            "index_of_multiple_deprivation": 3888,
            "latitude": 57.14959,
            "lep1": null,
            "lep1_id": null,
            "lep2": null,
            "lep2_id": null,
            "longitude": -2.096923,
            "lsoa": "George Street - 02",
            "lsoa11": "George Street - 02",
            "lsoa11_id": "S01006646",
            "lsoa21": "George Street - 02",
            "lsoa21_id": "S01013627",
            "lsoa_id": "S01013627",
            "msoa": "George Street",
            "msoa11": "George Street",
            "msoa11_id": "S02001261",
            "msoa21": "George Street",
            "msoa21_id": "S02002541",
            "msoa_id": "S02002541",
            "national_park": null,
            "national_park_id": null,
            "nhs_ha": "Grampian",
            "nhs_region": null,
            "nhs_region_id": null,
            "northings": 806529,
            "nuts": "Aberdeen City",
            "nuts_code": "TLM50",
            "nuts_id": "S30000026",
            "oa21_id": "S00136377",
            "outcode": "AB10",
            "parish": null,
            "parish_id": null,
            "parliamentary_constituency": "Aberdeen South",
            "pc_compact": "AB101AB",
            "pfa": "Scotland",
            "pfa_id": "S23000009",
            "postcode": "AB10 1AB",
            "primary_care_trust": "Aberdeen City Community Health Partnership",
            "quality": 1,
            "region": null,
            "ruc11": "(Scotland) Large Urban Area",
            "ruc11_id": "1",
            "ruc21": "Large Urban Areas",
            "ruc21_id": "1",
            "ttwa": "Aberdeen",
            "ttwa_id": "S22000047",
          },
        ]
      `);
    });
    it("returns prefix matches for outcode-only query", async () => {
      expect(await search({ postcode: "AB10" })).toMatchInlineSnapshot(`
        [
          {
            "admin_county": null,
            "admin_county_id": null,
            "admin_district": "Aberdeen City",
            "admin_district_id": "S12000033",
            "admin_ward": "George St/Harbour",
            "admin_ward_id": "S13002842",
            "bua": null,
            "bua_id": null,
            "cancer_alliance": null,
            "cancer_alliance_id": null,
            "ccg": "Aberdeen City Community Health Partnership",
            "ccg_code": "012",
            "ccg_id": "S03000012",
            "ced": null,
            "ced_id": null,
            "constituency_id": "S14000061",
            "country": "Scotland",
            "date_of_introduction": "201106",
            "date_of_termination": null,
            "eastings": 394235,
            "european_electoral_region": "Scotland",
            "icb": null,
            "icb_id": null,
            "incode": "1AB",
            "index_of_multiple_deprivation": 3888,
            "latitude": 57.14959,
            "lep1": null,
            "lep1_id": null,
            "lep2": null,
            "lep2_id": null,
            "longitude": -2.096923,
            "lsoa": "George Street - 02",
            "lsoa11": "George Street - 02",
            "lsoa11_id": "S01006646",
            "lsoa21": "George Street - 02",
            "lsoa21_id": "S01013627",
            "lsoa_id": "S01013627",
            "msoa": "George Street",
            "msoa11": "George Street",
            "msoa11_id": "S02001261",
            "msoa21": "George Street",
            "msoa21_id": "S02002541",
            "msoa_id": "S02002541",
            "national_park": null,
            "national_park_id": null,
            "nhs_ha": "Grampian",
            "nhs_region": null,
            "nhs_region_id": null,
            "northings": 806529,
            "nuts": "Aberdeen City",
            "nuts_code": "TLM50",
            "nuts_id": "S30000026",
            "oa21_id": "S00136377",
            "outcode": "AB10",
            "parish": null,
            "parish_id": null,
            "parliamentary_constituency": "Aberdeen South",
            "pc_compact": "AB101AB",
            "pfa": "Scotland",
            "pfa_id": "S23000009",
            "postcode": "AB10 1AB",
            "primary_care_trust": "Aberdeen City Community Health Partnership",
            "quality": 1,
            "region": null,
            "ruc11": "(Scotland) Large Urban Area",
            "ruc11_id": "1",
            "ruc21": "Large Urban Areas",
            "ruc21_id": "1",
            "ttwa": "Aberdeen",
            "ttwa_id": "S22000047",
          },
          {
            "admin_county": null,
            "admin_county_id": null,
            "admin_district": "Aberdeen City",
            "admin_district_id": "S12000033",
            "admin_ward": "George St/Harbour",
            "admin_ward_id": "S13002842",
            "bua": null,
            "bua_id": null,
            "cancer_alliance": null,
            "cancer_alliance_id": null,
            "ccg": "Aberdeen City Community Health Partnership",
            "ccg_code": "012",
            "ccg_id": "S03000012",
            "ced": null,
            "ced_id": null,
            "constituency_id": "S14000061",
            "country": "Scotland",
            "date_of_introduction": "199606",
            "date_of_termination": null,
            "eastings": 394235,
            "european_electoral_region": "Scotland",
            "icb": null,
            "icb_id": null,
            "incode": "1AF",
            "index_of_multiple_deprivation": 3888,
            "latitude": 57.14959,
            "lep1": null,
            "lep1_id": null,
            "lep2": null,
            "lep2_id": null,
            "longitude": -2.096923,
            "lsoa": "George Street - 02",
            "lsoa11": "George Street - 02",
            "lsoa11_id": "S01006646",
            "lsoa21": "George Street - 02",
            "lsoa21_id": "S01013627",
            "lsoa_id": "S01013627",
            "msoa": "George Street",
            "msoa11": "George Street",
            "msoa11_id": "S02001261",
            "msoa21": "George Street",
            "msoa21_id": "S02002541",
            "msoa_id": "S02002541",
            "national_park": null,
            "national_park_id": null,
            "nhs_ha": "Grampian",
            "nhs_region": null,
            "nhs_region_id": null,
            "northings": 806529,
            "nuts": "Aberdeen City",
            "nuts_code": "TLM50",
            "nuts_id": "S30000026",
            "oa21_id": "S00136377",
            "outcode": "AB10",
            "parish": null,
            "parish_id": null,
            "parliamentary_constituency": "Aberdeen South",
            "pc_compact": "AB101AF",
            "pfa": "Scotland",
            "pfa_id": "S23000009",
            "postcode": "AB10 1AF",
            "primary_care_trust": "Aberdeen City Community Health Partnership",
            "quality": 1,
            "region": null,
            "ruc11": "(Scotland) Large Urban Area",
            "ruc11_id": "1",
            "ruc21": "Large Urban Areas",
            "ruc21_id": "1",
            "ttwa": "Aberdeen",
            "ttwa_id": "S22000047",
          },
          {
            "admin_county": null,
            "admin_county_id": null,
            "admin_district": "Aberdeen City",
            "admin_district_id": "S12000033",
            "admin_ward": "George St/Harbour",
            "admin_ward_id": "S13002842",
            "bua": null,
            "bua_id": null,
            "cancer_alliance": null,
            "cancer_alliance_id": null,
            "ccg": "Aberdeen City Community Health Partnership",
            "ccg_code": "012",
            "ccg_id": "S03000012",
            "ced": null,
            "ced_id": null,
            "constituency_id": "S14000061",
            "country": "Scotland",
            "date_of_introduction": "199606",
            "date_of_termination": null,
            "eastings": 394230,
            "european_electoral_region": "Scotland",
            "icb": null,
            "icb_id": null,
            "incode": "1AG",
            "index_of_multiple_deprivation": 3888,
            "latitude": 57.149051,
            "lep1": null,
            "lep1_id": null,
            "lep2": null,
            "lep2_id": null,
            "longitude": -2.097004,
            "lsoa": "George Street - 02",
            "lsoa11": "George Street - 02",
            "lsoa11_id": "S01006646",
            "lsoa21": "George Street - 02",
            "lsoa21_id": "S01013627",
            "lsoa_id": "S01013627",
            "msoa": "George Street",
            "msoa11": "George Street",
            "msoa11_id": "S02001261",
            "msoa21": "George Street",
            "msoa21_id": "S02002541",
            "msoa_id": "S02002541",
            "national_park": null,
            "national_park_id": null,
            "nhs_ha": "Grampian",
            "nhs_region": null,
            "nhs_region_id": null,
            "northings": 806469,
            "nuts": "Aberdeen City",
            "nuts_code": "TLM50",
            "nuts_id": "S30000026",
            "oa21_id": "S00136377",
            "outcode": "AB10",
            "parish": null,
            "parish_id": null,
            "parliamentary_constituency": "Aberdeen South",
            "pc_compact": "AB101AG",
            "pfa": "Scotland",
            "pfa_id": "S23000009",
            "postcode": "AB10 1AG",
            "primary_care_trust": "Aberdeen City Community Health Partnership",
            "quality": 1,
            "region": null,
            "ruc11": "(Scotland) Large Urban Area",
            "ruc11_id": "1",
            "ruc21": "Large Urban Areas",
            "ruc21_id": "1",
            "ttwa": "Aberdeen",
            "ttwa_id": "S22000047",
          },
          {
            "admin_county": null,
            "admin_county_id": null,
            "admin_district": "Aberdeen City",
            "admin_district_id": "S12000033",
            "admin_ward": "George St/Harbour",
            "admin_ward_id": "S13002842",
            "bua": null,
            "bua_id": null,
            "cancer_alliance": null,
            "cancer_alliance_id": null,
            "ccg": "Aberdeen City Community Health Partnership",
            "ccg_code": "012",
            "ccg_id": "S03000012",
            "ced": null,
            "ced_id": null,
            "constituency_id": "S14000061",
            "country": "Scotland",
            "date_of_introduction": "199606",
            "date_of_termination": null,
            "eastings": 394235,
            "european_electoral_region": "Scotland",
            "icb": null,
            "icb_id": null,
            "incode": "1AH",
            "index_of_multiple_deprivation": 3888,
            "latitude": 57.14959,
            "lep1": null,
            "lep1_id": null,
            "lep2": null,
            "lep2_id": null,
            "longitude": -2.096923,
            "lsoa": "George Street - 02",
            "lsoa11": "George Street - 02",
            "lsoa11_id": "S01006646",
            "lsoa21": "George Street - 02",
            "lsoa21_id": "S01013627",
            "lsoa_id": "S01013627",
            "msoa": "George Street",
            "msoa11": "George Street",
            "msoa11_id": "S02001261",
            "msoa21": "George Street",
            "msoa21_id": "S02002541",
            "msoa_id": "S02002541",
            "national_park": null,
            "national_park_id": null,
            "nhs_ha": "Grampian",
            "nhs_region": null,
            "nhs_region_id": null,
            "northings": 806529,
            "nuts": "Aberdeen City",
            "nuts_code": "TLM50",
            "nuts_id": "S30000026",
            "oa21_id": "S00136377",
            "outcode": "AB10",
            "parish": null,
            "parish_id": null,
            "parliamentary_constituency": "Aberdeen South",
            "pc_compact": "AB101AH",
            "pfa": "Scotland",
            "pfa_id": "S23000009",
            "postcode": "AB10 1AH",
            "primary_care_trust": "Aberdeen City Community Health Partnership",
            "quality": 1,
            "region": null,
            "ruc11": "(Scotland) Large Urban Area",
            "ruc11_id": "1",
            "ruc21": "Large Urban Areas",
            "ruc21_id": "1",
            "ttwa": "Aberdeen",
            "ttwa_id": "S22000047",
          },
          {
            "admin_county": null,
            "admin_county_id": null,
            "admin_district": "Aberdeen City",
            "admin_district_id": "S12000033",
            "admin_ward": "George St/Harbour",
            "admin_ward_id": "S13002842",
            "bua": null,
            "bua_id": null,
            "cancer_alliance": null,
            "cancer_alliance_id": null,
            "ccg": "Aberdeen City Community Health Partnership",
            "ccg_code": "012",
            "ccg_id": "S03000012",
            "ced": null,
            "ced_id": null,
            "constituency_id": "S14000061",
            "country": "Scotland",
            "date_of_introduction": "199606",
            "date_of_termination": null,
            "eastings": 394296,
            "european_electoral_region": "Scotland",
            "icb": null,
            "icb_id": null,
            "incode": "1AL",
            "index_of_multiple_deprivation": 3888,
            "latitude": 57.150058,
            "lep1": null,
            "lep1_id": null,
            "lep2": null,
            "lep2_id": null,
            "longitude": -2.095916,
            "lsoa": "George Street - 02",
            "lsoa11": "George Street - 02",
            "lsoa11_id": "S01006646",
            "lsoa21": "George Street - 02",
            "lsoa21_id": "S01013627",
            "lsoa_id": "S01013627",
            "msoa": "George Street",
            "msoa11": "George Street",
            "msoa11_id": "S02001261",
            "msoa21": "George Street",
            "msoa21_id": "S02002541",
            "msoa_id": "S02002541",
            "national_park": null,
            "national_park_id": null,
            "nhs_ha": "Grampian",
            "nhs_region": null,
            "nhs_region_id": null,
            "northings": 806581,
            "nuts": "Aberdeen City",
            "nuts_code": "TLM50",
            "nuts_id": "S30000026",
            "oa21_id": "S00136377",
            "outcode": "AB10",
            "parish": null,
            "parish_id": null,
            "parliamentary_constituency": "Aberdeen South",
            "pc_compact": "AB101AL",
            "pfa": "Scotland",
            "pfa_id": "S23000009",
            "postcode": "AB10 1AL",
            "primary_care_trust": "Aberdeen City Community Health Partnership",
            "quality": 1,
            "region": null,
            "ruc11": "(Scotland) Large Urban Area",
            "ruc11_id": "1",
            "ruc21": "Large Urban Areas",
            "ruc21_id": "1",
            "ttwa": "Aberdeen",
            "ttwa_id": "S22000047",
          },
          {
            "admin_county": null,
            "admin_county_id": null,
            "admin_district": "Aberdeen City",
            "admin_district_id": "S12000033",
            "admin_ward": "George St/Harbour",
            "admin_ward_id": "S13002842",
            "bua": null,
            "bua_id": null,
            "cancer_alliance": null,
            "cancer_alliance_id": null,
            "ccg": "Aberdeen City Community Health Partnership",
            "ccg_code": "012",
            "ccg_id": "S03000012",
            "ced": null,
            "ced_id": null,
            "constituency_id": "S14000061",
            "country": "Scotland",
            "date_of_introduction": "199606",
            "date_of_termination": null,
            "eastings": 394367,
            "european_electoral_region": "Scotland",
            "icb": null,
            "icb_id": null,
            "incode": "1AN",
            "index_of_multiple_deprivation": 3888,
            "latitude": 57.149699,
            "lep1": null,
            "lep1_id": null,
            "lep2": null,
            "lep2_id": null,
            "longitude": -2.094742,
            "lsoa": "George Street - 02",
            "lsoa11": "George Street - 02",
            "lsoa11_id": "S01006646",
            "lsoa21": "George Street - 02",
            "lsoa21_id": "S01013627",
            "lsoa_id": "S01013627",
            "msoa": "George Street",
            "msoa11": "George Street",
            "msoa11_id": "S02001261",
            "msoa21": "George Street",
            "msoa21_id": "S02002541",
            "msoa_id": "S02002541",
            "national_park": null,
            "national_park_id": null,
            "nhs_ha": "Grampian",
            "nhs_region": null,
            "nhs_region_id": null,
            "northings": 806541,
            "nuts": "Aberdeen City",
            "nuts_code": "TLM50",
            "nuts_id": "S30000026",
            "oa21_id": "S00136377",
            "outcode": "AB10",
            "parish": null,
            "parish_id": null,
            "parliamentary_constituency": "Aberdeen South",
            "pc_compact": "AB101AN",
            "pfa": "Scotland",
            "pfa_id": "S23000009",
            "postcode": "AB10 1AN",
            "primary_care_trust": "Aberdeen City Community Health Partnership",
            "quality": 1,
            "region": null,
            "ruc11": "(Scotland) Large Urban Area",
            "ruc11_id": "1",
            "ruc21": "Large Urban Areas",
            "ruc21_id": "1",
            "ttwa": "Aberdeen",
            "ttwa_id": "S22000047",
          },
          {
            "admin_county": null,
            "admin_county_id": null,
            "admin_district": "Aberdeen City",
            "admin_district_id": "S12000033",
            "admin_ward": "George St/Harbour",
            "admin_ward_id": "S13002842",
            "bua": null,
            "bua_id": null,
            "cancer_alliance": null,
            "cancer_alliance_id": null,
            "ccg": "Aberdeen City Community Health Partnership",
            "ccg_code": "012",
            "ccg_id": "S03000012",
            "ced": null,
            "ced_id": null,
            "constituency_id": "S14000061",
            "country": "Scotland",
            "date_of_introduction": "199606",
            "date_of_termination": null,
            "eastings": 394309,
            "european_electoral_region": "Scotland",
            "icb": null,
            "icb_id": null,
            "incode": "1AP",
            "index_of_multiple_deprivation": 3888,
            "latitude": 57.148962,
            "lep1": null,
            "lep1_id": null,
            "lep2": null,
            "lep2_id": null,
            "longitude": -2.095699,
            "lsoa": "George Street - 02",
            "lsoa11": "George Street - 02",
            "lsoa11_id": "S01006646",
            "lsoa21": "George Street - 02",
            "lsoa21_id": "S01013627",
            "lsoa_id": "S01013627",
            "msoa": "George Street",
            "msoa11": "George Street",
            "msoa11_id": "S02001261",
            "msoa21": "George Street",
            "msoa21_id": "S02002541",
            "msoa_id": "S02002541",
            "national_park": null,
            "national_park_id": null,
            "nhs_ha": "Grampian",
            "nhs_region": null,
            "nhs_region_id": null,
            "northings": 806459,
            "nuts": "Aberdeen City",
            "nuts_code": "TLM50",
            "nuts_id": "S30000026",
            "oa21_id": "S00136377",
            "outcode": "AB10",
            "parish": null,
            "parish_id": null,
            "parliamentary_constituency": "Aberdeen South",
            "pc_compact": "AB101AP",
            "pfa": "Scotland",
            "pfa_id": "S23000009",
            "postcode": "AB10 1AP",
            "primary_care_trust": "Aberdeen City Community Health Partnership",
            "quality": 1,
            "region": null,
            "ruc11": "(Scotland) Large Urban Area",
            "ruc11_id": "1",
            "ruc21": "Large Urban Areas",
            "ruc21_id": "1",
            "ttwa": "Aberdeen",
            "ttwa_id": "S22000047",
          },
          {
            "admin_county": null,
            "admin_county_id": null,
            "admin_district": "Aberdeen City",
            "admin_district_id": "S12000033",
            "admin_ward": "George St/Harbour",
            "admin_ward_id": "S13002842",
            "bua": null,
            "bua_id": null,
            "cancer_alliance": null,
            "cancer_alliance_id": null,
            "ccg": "Aberdeen City Community Health Partnership",
            "ccg_code": "012",
            "ccg_id": "S03000012",
            "ced": null,
            "ced_id": null,
            "constituency_id": "S14000061",
            "country": "Scotland",
            "date_of_introduction": "199606",
            "date_of_termination": null,
            "eastings": 394230,
            "european_electoral_region": "Scotland",
            "icb": null,
            "icb_id": null,
            "incode": "1AQ",
            "index_of_multiple_deprivation": 3888,
            "latitude": 57.149051,
            "lep1": null,
            "lep1_id": null,
            "lep2": null,
            "lep2_id": null,
            "longitude": -2.097004,
            "lsoa": "George Street - 02",
            "lsoa11": "George Street - 02",
            "lsoa11_id": "S01006646",
            "lsoa21": "George Street - 02",
            "lsoa21_id": "S01013627",
            "lsoa_id": "S01013627",
            "msoa": "George Street",
            "msoa11": "George Street",
            "msoa11_id": "S02001261",
            "msoa21": "George Street",
            "msoa21_id": "S02002541",
            "msoa_id": "S02002541",
            "national_park": null,
            "national_park_id": null,
            "nhs_ha": "Grampian",
            "nhs_region": null,
            "nhs_region_id": null,
            "northings": 806469,
            "nuts": "Aberdeen City",
            "nuts_code": "TLM50",
            "nuts_id": "S30000026",
            "oa21_id": "S00136377",
            "outcode": "AB10",
            "parish": null,
            "parish_id": null,
            "parliamentary_constituency": "Aberdeen South",
            "pc_compact": "AB101AQ",
            "pfa": "Scotland",
            "pfa_id": "S23000009",
            "postcode": "AB10 1AQ",
            "primary_care_trust": "Aberdeen City Community Health Partnership",
            "quality": 1,
            "region": null,
            "ruc11": "(Scotland) Large Urban Area",
            "ruc11_id": "1",
            "ruc21": "Large Urban Areas",
            "ruc21_id": "1",
            "ttwa": "Aberdeen",
            "ttwa_id": "S22000047",
          },
          {
            "admin_county": null,
            "admin_county_id": null,
            "admin_district": "Aberdeen City",
            "admin_district_id": "S12000033",
            "admin_ward": "George St/Harbour",
            "admin_ward_id": "S13002842",
            "bua": null,
            "bua_id": null,
            "cancer_alliance": null,
            "cancer_alliance_id": null,
            "ccg": "Aberdeen City Community Health Partnership",
            "ccg_code": "012",
            "ccg_id": "S03000012",
            "ced": null,
            "ced_id": null,
            "constituency_id": "S14000061",
            "country": "Scotland",
            "date_of_introduction": "199606",
            "date_of_termination": null,
            "eastings": 394235,
            "european_electoral_region": "Scotland",
            "icb": null,
            "icb_id": null,
            "incode": "1AR",
            "index_of_multiple_deprivation": 3888,
            "latitude": 57.14959,
            "lep1": null,
            "lep1_id": null,
            "lep2": null,
            "lep2_id": null,
            "longitude": -2.096923,
            "lsoa": "George Street - 02",
            "lsoa11": "George Street - 02",
            "lsoa11_id": "S01006646",
            "lsoa21": "George Street - 02",
            "lsoa21_id": "S01013627",
            "lsoa_id": "S01013627",
            "msoa": "George Street",
            "msoa11": "George Street",
            "msoa11_id": "S02001261",
            "msoa21": "George Street",
            "msoa21_id": "S02002541",
            "msoa_id": "S02002541",
            "national_park": null,
            "national_park_id": null,
            "nhs_ha": "Grampian",
            "nhs_region": null,
            "nhs_region_id": null,
            "northings": 806529,
            "nuts": "Aberdeen City",
            "nuts_code": "TLM50",
            "nuts_id": "S30000026",
            "oa21_id": "S00136377",
            "outcode": "AB10",
            "parish": null,
            "parish_id": null,
            "parliamentary_constituency": "Aberdeen South",
            "pc_compact": "AB101AR",
            "pfa": "Scotland",
            "pfa_id": "S23000009",
            "postcode": "AB10 1AR",
            "primary_care_trust": "Aberdeen City Community Health Partnership",
            "quality": 1,
            "region": null,
            "ruc11": "(Scotland) Large Urban Area",
            "ruc11_id": "1",
            "ruc21": "Large Urban Areas",
            "ruc21_id": "1",
            "ttwa": "Aberdeen",
            "ttwa_id": "S22000047",
          },
          {
            "admin_county": null,
            "admin_county_id": null,
            "admin_district": "Aberdeen City",
            "admin_district_id": "S12000033",
            "admin_ward": "George St/Harbour",
            "admin_ward_id": "S13002842",
            "bua": null,
            "bua_id": null,
            "cancer_alliance": null,
            "cancer_alliance_id": null,
            "ccg": "Aberdeen City Community Health Partnership",
            "ccg_code": "012",
            "ccg_id": "S03000012",
            "ced": null,
            "ced_id": null,
            "constituency_id": "S14000061",
            "country": "Scotland",
            "date_of_introduction": "199606",
            "date_of_termination": null,
            "eastings": 394198,
            "european_electoral_region": "Scotland",
            "icb": null,
            "icb_id": null,
            "incode": "1AS",
            "index_of_multiple_deprivation": 3888,
            "latitude": 57.148296,
            "lep1": null,
            "lep1_id": null,
            "lep2": null,
            "lep2_id": null,
            "longitude": -2.097531,
            "lsoa": "George Street - 02",
            "lsoa11": "George Street - 02",
            "lsoa11_id": "S01006646",
            "lsoa21": "George Street - 02",
            "lsoa21_id": "S01013627",
            "lsoa_id": "S01013627",
            "msoa": "George Street",
            "msoa11": "George Street",
            "msoa11_id": "S02001261",
            "msoa21": "George Street",
            "msoa21_id": "S02002541",
            "msoa_id": "S02002541",
            "national_park": null,
            "national_park_id": null,
            "nhs_ha": "Grampian",
            "nhs_region": null,
            "nhs_region_id": null,
            "northings": 806385,
            "nuts": "Aberdeen City",
            "nuts_code": "TLM50",
            "nuts_id": "S30000026",
            "oa21_id": "S00136377",
            "outcode": "AB10",
            "parish": null,
            "parish_id": null,
            "parliamentary_constituency": "Aberdeen South",
            "pc_compact": "AB101AS",
            "pfa": "Scotland",
            "pfa_id": "S23000009",
            "postcode": "AB10 1AS",
            "primary_care_trust": "Aberdeen City Community Health Partnership",
            "quality": 1,
            "region": null,
            "ruc11": "(Scotland) Large Urban Area",
            "ruc11_id": "1",
            "ruc21": "Large Urban Areas",
            "ruc21_id": "1",
            "ttwa": "Aberdeen",
            "ttwa_id": "S22000047",
          },
        ]
      `);
    });
    it("honours the limit parameter", async () => {
      expect(
        await search({ postcode: "AB10", limit: "3" })
      ).toMatchInlineSnapshot(`
        [
          {
            "admin_county": null,
            "admin_county_id": null,
            "admin_district": "Aberdeen City",
            "admin_district_id": "S12000033",
            "admin_ward": "George St/Harbour",
            "admin_ward_id": "S13002842",
            "bua": null,
            "bua_id": null,
            "cancer_alliance": null,
            "cancer_alliance_id": null,
            "ccg": "Aberdeen City Community Health Partnership",
            "ccg_code": "012",
            "ccg_id": "S03000012",
            "ced": null,
            "ced_id": null,
            "constituency_id": "S14000061",
            "country": "Scotland",
            "date_of_introduction": "201106",
            "date_of_termination": null,
            "eastings": 394235,
            "european_electoral_region": "Scotland",
            "icb": null,
            "icb_id": null,
            "incode": "1AB",
            "index_of_multiple_deprivation": 3888,
            "latitude": 57.14959,
            "lep1": null,
            "lep1_id": null,
            "lep2": null,
            "lep2_id": null,
            "longitude": -2.096923,
            "lsoa": "George Street - 02",
            "lsoa11": "George Street - 02",
            "lsoa11_id": "S01006646",
            "lsoa21": "George Street - 02",
            "lsoa21_id": "S01013627",
            "lsoa_id": "S01013627",
            "msoa": "George Street",
            "msoa11": "George Street",
            "msoa11_id": "S02001261",
            "msoa21": "George Street",
            "msoa21_id": "S02002541",
            "msoa_id": "S02002541",
            "national_park": null,
            "national_park_id": null,
            "nhs_ha": "Grampian",
            "nhs_region": null,
            "nhs_region_id": null,
            "northings": 806529,
            "nuts": "Aberdeen City",
            "nuts_code": "TLM50",
            "nuts_id": "S30000026",
            "oa21_id": "S00136377",
            "outcode": "AB10",
            "parish": null,
            "parish_id": null,
            "parliamentary_constituency": "Aberdeen South",
            "pc_compact": "AB101AB",
            "pfa": "Scotland",
            "pfa_id": "S23000009",
            "postcode": "AB10 1AB",
            "primary_care_trust": "Aberdeen City Community Health Partnership",
            "quality": 1,
            "region": null,
            "ruc11": "(Scotland) Large Urban Area",
            "ruc11_id": "1",
            "ruc21": "Large Urban Areas",
            "ruc21_id": "1",
            "ttwa": "Aberdeen",
            "ttwa_id": "S22000047",
          },
          {
            "admin_county": null,
            "admin_county_id": null,
            "admin_district": "Aberdeen City",
            "admin_district_id": "S12000033",
            "admin_ward": "George St/Harbour",
            "admin_ward_id": "S13002842",
            "bua": null,
            "bua_id": null,
            "cancer_alliance": null,
            "cancer_alliance_id": null,
            "ccg": "Aberdeen City Community Health Partnership",
            "ccg_code": "012",
            "ccg_id": "S03000012",
            "ced": null,
            "ced_id": null,
            "constituency_id": "S14000061",
            "country": "Scotland",
            "date_of_introduction": "199606",
            "date_of_termination": null,
            "eastings": 394235,
            "european_electoral_region": "Scotland",
            "icb": null,
            "icb_id": null,
            "incode": "1AF",
            "index_of_multiple_deprivation": 3888,
            "latitude": 57.14959,
            "lep1": null,
            "lep1_id": null,
            "lep2": null,
            "lep2_id": null,
            "longitude": -2.096923,
            "lsoa": "George Street - 02",
            "lsoa11": "George Street - 02",
            "lsoa11_id": "S01006646",
            "lsoa21": "George Street - 02",
            "lsoa21_id": "S01013627",
            "lsoa_id": "S01013627",
            "msoa": "George Street",
            "msoa11": "George Street",
            "msoa11_id": "S02001261",
            "msoa21": "George Street",
            "msoa21_id": "S02002541",
            "msoa_id": "S02002541",
            "national_park": null,
            "national_park_id": null,
            "nhs_ha": "Grampian",
            "nhs_region": null,
            "nhs_region_id": null,
            "northings": 806529,
            "nuts": "Aberdeen City",
            "nuts_code": "TLM50",
            "nuts_id": "S30000026",
            "oa21_id": "S00136377",
            "outcode": "AB10",
            "parish": null,
            "parish_id": null,
            "parliamentary_constituency": "Aberdeen South",
            "pc_compact": "AB101AF",
            "pfa": "Scotland",
            "pfa_id": "S23000009",
            "postcode": "AB10 1AF",
            "primary_care_trust": "Aberdeen City Community Health Partnership",
            "quality": 1,
            "region": null,
            "ruc11": "(Scotland) Large Urban Area",
            "ruc11_id": "1",
            "ruc21": "Large Urban Areas",
            "ruc21_id": "1",
            "ttwa": "Aberdeen",
            "ttwa_id": "S22000047",
          },
          {
            "admin_county": null,
            "admin_county_id": null,
            "admin_district": "Aberdeen City",
            "admin_district_id": "S12000033",
            "admin_ward": "George St/Harbour",
            "admin_ward_id": "S13002842",
            "bua": null,
            "bua_id": null,
            "cancer_alliance": null,
            "cancer_alliance_id": null,
            "ccg": "Aberdeen City Community Health Partnership",
            "ccg_code": "012",
            "ccg_id": "S03000012",
            "ced": null,
            "ced_id": null,
            "constituency_id": "S14000061",
            "country": "Scotland",
            "date_of_introduction": "199606",
            "date_of_termination": null,
            "eastings": 394230,
            "european_electoral_region": "Scotland",
            "icb": null,
            "icb_id": null,
            "incode": "1AG",
            "index_of_multiple_deprivation": 3888,
            "latitude": 57.149051,
            "lep1": null,
            "lep1_id": null,
            "lep2": null,
            "lep2_id": null,
            "longitude": -2.097004,
            "lsoa": "George Street - 02",
            "lsoa11": "George Street - 02",
            "lsoa11_id": "S01006646",
            "lsoa21": "George Street - 02",
            "lsoa21_id": "S01013627",
            "lsoa_id": "S01013627",
            "msoa": "George Street",
            "msoa11": "George Street",
            "msoa11_id": "S02001261",
            "msoa21": "George Street",
            "msoa21_id": "S02002541",
            "msoa_id": "S02002541",
            "national_park": null,
            "national_park_id": null,
            "nhs_ha": "Grampian",
            "nhs_region": null,
            "nhs_region_id": null,
            "northings": 806469,
            "nuts": "Aberdeen City",
            "nuts_code": "TLM50",
            "nuts_id": "S30000026",
            "oa21_id": "S00136377",
            "outcode": "AB10",
            "parish": null,
            "parish_id": null,
            "parliamentary_constituency": "Aberdeen South",
            "pc_compact": "AB101AG",
            "pfa": "Scotland",
            "pfa_id": "S23000009",
            "postcode": "AB10 1AG",
            "primary_care_trust": "Aberdeen City Community Health Partnership",
            "quality": 1,
            "region": null,
            "ruc11": "(Scotland) Large Urban Area",
            "ruc11_id": "1",
            "ruc21": "Large Urban Areas",
            "ruc21_id": "1",
            "ttwa": "Aberdeen",
            "ttwa_id": "S22000047",
          },
        ]
      `);
    });
    it("clamps limit above MAX to MAX", async () => {
      const rows = await search({ postcode: "AB1", limit: "9999" });
      // Row payload is huge; just snapshot the length.
      expect(rows?.length ?? null).toMatchInlineSnapshot(`100`);
    });
    it("is insensitive to case", async () => {
      expect(await search({ postcode: "ab10 1ab" })).toMatchInlineSnapshot(`
        [
          {
            "admin_county": null,
            "admin_county_id": null,
            "admin_district": "Aberdeen City",
            "admin_district_id": "S12000033",
            "admin_ward": "George St/Harbour",
            "admin_ward_id": "S13002842",
            "bua": null,
            "bua_id": null,
            "cancer_alliance": null,
            "cancer_alliance_id": null,
            "ccg": "Aberdeen City Community Health Partnership",
            "ccg_code": "012",
            "ccg_id": "S03000012",
            "ced": null,
            "ced_id": null,
            "constituency_id": "S14000061",
            "country": "Scotland",
            "date_of_introduction": "201106",
            "date_of_termination": null,
            "eastings": 394235,
            "european_electoral_region": "Scotland",
            "icb": null,
            "icb_id": null,
            "incode": "1AB",
            "index_of_multiple_deprivation": 3888,
            "latitude": 57.14959,
            "lep1": null,
            "lep1_id": null,
            "lep2": null,
            "lep2_id": null,
            "longitude": -2.096923,
            "lsoa": "George Street - 02",
            "lsoa11": "George Street - 02",
            "lsoa11_id": "S01006646",
            "lsoa21": "George Street - 02",
            "lsoa21_id": "S01013627",
            "lsoa_id": "S01013627",
            "msoa": "George Street",
            "msoa11": "George Street",
            "msoa11_id": "S02001261",
            "msoa21": "George Street",
            "msoa21_id": "S02002541",
            "msoa_id": "S02002541",
            "national_park": null,
            "national_park_id": null,
            "nhs_ha": "Grampian",
            "nhs_region": null,
            "nhs_region_id": null,
            "northings": 806529,
            "nuts": "Aberdeen City",
            "nuts_code": "TLM50",
            "nuts_id": "S30000026",
            "oa21_id": "S00136377",
            "outcode": "AB10",
            "parish": null,
            "parish_id": null,
            "parliamentary_constituency": "Aberdeen South",
            "pc_compact": "AB101AB",
            "pfa": "Scotland",
            "pfa_id": "S23000009",
            "postcode": "AB10 1AB",
            "primary_care_trust": "Aberdeen City Community Health Partnership",
            "quality": 1,
            "region": null,
            "ruc11": "(Scotland) Large Urban Area",
            "ruc11_id": "1",
            "ruc21": "Large Urban Areas",
            "ruc21_id": "1",
            "ttwa": "Aberdeen",
            "ttwa_id": "S22000047",
          },
        ]
      `);
    });
  });

  describe("nearestPostcodes()", () => {
    it("returns nearest within radius, ordered by distance", async () => {
      expect(
        await nearestPostcodes({ ...ANCHOR, radius: "1000", limit: "5" })
      ).toMatchInlineSnapshot(`
        [
          {
            "admin_county": null,
            "admin_county_id": null,
            "admin_district": "Aberdeen City",
            "admin_district_id": "S12000033",
            "admin_ward": "George St/Harbour",
            "admin_ward_id": "S13002842",
            "bua": null,
            "bua_id": null,
            "cancer_alliance": null,
            "cancer_alliance_id": null,
            "ccg": "Aberdeen City Community Health Partnership",
            "ccg_code": "012",
            "ccg_id": "S03000012",
            "ced": null,
            "ced_id": null,
            "constituency_id": "S14000061",
            "country": "Scotland",
            "date_of_introduction": "201106",
            "date_of_termination": null,
            "distance": 0,
            "eastings": 394235,
            "european_electoral_region": "Scotland",
            "icb": null,
            "icb_id": null,
            "incode": "1AB",
            "index_of_multiple_deprivation": 3888,
            "latitude": 57.14959,
            "lep1": null,
            "lep1_id": null,
            "lep2": null,
            "lep2_id": null,
            "longitude": -2.096923,
            "lsoa": "George Street - 02",
            "lsoa11": "George Street - 02",
            "lsoa11_id": "S01006646",
            "lsoa21": "George Street - 02",
            "lsoa21_id": "S01013627",
            "lsoa_id": "S01013627",
            "msoa": "George Street",
            "msoa11": "George Street",
            "msoa11_id": "S02001261",
            "msoa21": "George Street",
            "msoa21_id": "S02002541",
            "msoa_id": "S02002541",
            "national_park": null,
            "national_park_id": null,
            "nhs_ha": "Grampian",
            "nhs_region": null,
            "nhs_region_id": null,
            "northings": 806529,
            "nuts": "Aberdeen City",
            "nuts_code": "TLM50",
            "nuts_id": "S30000026",
            "oa21_id": "S00136377",
            "outcode": "AB10",
            "parish": null,
            "parish_id": null,
            "parliamentary_constituency": "Aberdeen South",
            "pc_compact": "AB101AB",
            "pfa": "Scotland",
            "pfa_id": "S23000009",
            "postcode": "AB10 1AB",
            "primary_care_trust": "Aberdeen City Community Health Partnership",
            "quality": 1,
            "region": null,
            "ruc11": "(Scotland) Large Urban Area",
            "ruc11_id": "1",
            "ruc21": "Large Urban Areas",
            "ruc21_id": "1",
            "ttwa": "Aberdeen",
            "ttwa_id": "S22000047",
          },
          {
            "admin_county": null,
            "admin_county_id": null,
            "admin_district": "Aberdeen City",
            "admin_district_id": "S12000033",
            "admin_ward": "George St/Harbour",
            "admin_ward_id": "S13002842",
            "bua": null,
            "bua_id": null,
            "cancer_alliance": null,
            "cancer_alliance_id": null,
            "ccg": "Aberdeen City Community Health Partnership",
            "ccg_code": "012",
            "ccg_id": "S03000012",
            "ced": null,
            "ced_id": null,
            "constituency_id": "S14000061",
            "country": "Scotland",
            "date_of_introduction": "199606",
            "date_of_termination": null,
            "distance": 0,
            "eastings": 394235,
            "european_electoral_region": "Scotland",
            "icb": null,
            "icb_id": null,
            "incode": "1AF",
            "index_of_multiple_deprivation": 3888,
            "latitude": 57.14959,
            "lep1": null,
            "lep1_id": null,
            "lep2": null,
            "lep2_id": null,
            "longitude": -2.096923,
            "lsoa": "George Street - 02",
            "lsoa11": "George Street - 02",
            "lsoa11_id": "S01006646",
            "lsoa21": "George Street - 02",
            "lsoa21_id": "S01013627",
            "lsoa_id": "S01013627",
            "msoa": "George Street",
            "msoa11": "George Street",
            "msoa11_id": "S02001261",
            "msoa21": "George Street",
            "msoa21_id": "S02002541",
            "msoa_id": "S02002541",
            "national_park": null,
            "national_park_id": null,
            "nhs_ha": "Grampian",
            "nhs_region": null,
            "nhs_region_id": null,
            "northings": 806529,
            "nuts": "Aberdeen City",
            "nuts_code": "TLM50",
            "nuts_id": "S30000026",
            "oa21_id": "S00136377",
            "outcode": "AB10",
            "parish": null,
            "parish_id": null,
            "parliamentary_constituency": "Aberdeen South",
            "pc_compact": "AB101AF",
            "pfa": "Scotland",
            "pfa_id": "S23000009",
            "postcode": "AB10 1AF",
            "primary_care_trust": "Aberdeen City Community Health Partnership",
            "quality": 1,
            "region": null,
            "ruc11": "(Scotland) Large Urban Area",
            "ruc11_id": "1",
            "ruc21": "Large Urban Areas",
            "ruc21_id": "1",
            "ttwa": "Aberdeen",
            "ttwa_id": "S22000047",
          },
          {
            "admin_county": null,
            "admin_county_id": null,
            "admin_district": "Aberdeen City",
            "admin_district_id": "S12000033",
            "admin_ward": "George St/Harbour",
            "admin_ward_id": "S13002842",
            "bua": null,
            "bua_id": null,
            "cancer_alliance": null,
            "cancer_alliance_id": null,
            "ccg": "Aberdeen City Community Health Partnership",
            "ccg_code": "012",
            "ccg_id": "S03000012",
            "ced": null,
            "ced_id": null,
            "constituency_id": "S14000061",
            "country": "Scotland",
            "date_of_introduction": "199606",
            "date_of_termination": null,
            "distance": 0,
            "eastings": 394235,
            "european_electoral_region": "Scotland",
            "icb": null,
            "icb_id": null,
            "incode": "1AH",
            "index_of_multiple_deprivation": 3888,
            "latitude": 57.14959,
            "lep1": null,
            "lep1_id": null,
            "lep2": null,
            "lep2_id": null,
            "longitude": -2.096923,
            "lsoa": "George Street - 02",
            "lsoa11": "George Street - 02",
            "lsoa11_id": "S01006646",
            "lsoa21": "George Street - 02",
            "lsoa21_id": "S01013627",
            "lsoa_id": "S01013627",
            "msoa": "George Street",
            "msoa11": "George Street",
            "msoa11_id": "S02001261",
            "msoa21": "George Street",
            "msoa21_id": "S02002541",
            "msoa_id": "S02002541",
            "national_park": null,
            "national_park_id": null,
            "nhs_ha": "Grampian",
            "nhs_region": null,
            "nhs_region_id": null,
            "northings": 806529,
            "nuts": "Aberdeen City",
            "nuts_code": "TLM50",
            "nuts_id": "S30000026",
            "oa21_id": "S00136377",
            "outcode": "AB10",
            "parish": null,
            "parish_id": null,
            "parliamentary_constituency": "Aberdeen South",
            "pc_compact": "AB101AH",
            "pfa": "Scotland",
            "pfa_id": "S23000009",
            "postcode": "AB10 1AH",
            "primary_care_trust": "Aberdeen City Community Health Partnership",
            "quality": 1,
            "region": null,
            "ruc11": "(Scotland) Large Urban Area",
            "ruc11_id": "1",
            "ruc21": "Large Urban Areas",
            "ruc21_id": "1",
            "ttwa": "Aberdeen",
            "ttwa_id": "S22000047",
          },
          {
            "admin_county": null,
            "admin_county_id": null,
            "admin_district": "Aberdeen City",
            "admin_district_id": "S12000033",
            "admin_ward": "George St/Harbour",
            "admin_ward_id": "S13002842",
            "bua": null,
            "bua_id": null,
            "cancer_alliance": null,
            "cancer_alliance_id": null,
            "ccg": "Aberdeen City Community Health Partnership",
            "ccg_code": "012",
            "ccg_id": "S03000012",
            "ced": null,
            "ced_id": null,
            "constituency_id": "S14000061",
            "country": "Scotland",
            "date_of_introduction": "199606",
            "date_of_termination": null,
            "distance": 0,
            "eastings": 394235,
            "european_electoral_region": "Scotland",
            "icb": null,
            "icb_id": null,
            "incode": "1AR",
            "index_of_multiple_deprivation": 3888,
            "latitude": 57.14959,
            "lep1": null,
            "lep1_id": null,
            "lep2": null,
            "lep2_id": null,
            "longitude": -2.096923,
            "lsoa": "George Street - 02",
            "lsoa11": "George Street - 02",
            "lsoa11_id": "S01006646",
            "lsoa21": "George Street - 02",
            "lsoa21_id": "S01013627",
            "lsoa_id": "S01013627",
            "msoa": "George Street",
            "msoa11": "George Street",
            "msoa11_id": "S02001261",
            "msoa21": "George Street",
            "msoa21_id": "S02002541",
            "msoa_id": "S02002541",
            "national_park": null,
            "national_park_id": null,
            "nhs_ha": "Grampian",
            "nhs_region": null,
            "nhs_region_id": null,
            "northings": 806529,
            "nuts": "Aberdeen City",
            "nuts_code": "TLM50",
            "nuts_id": "S30000026",
            "oa21_id": "S00136377",
            "outcode": "AB10",
            "parish": null,
            "parish_id": null,
            "parliamentary_constituency": "Aberdeen South",
            "pc_compact": "AB101AR",
            "pfa": "Scotland",
            "pfa_id": "S23000009",
            "postcode": "AB10 1AR",
            "primary_care_trust": "Aberdeen City Community Health Partnership",
            "quality": 1,
            "region": null,
            "ruc11": "(Scotland) Large Urban Area",
            "ruc11_id": "1",
            "ruc21": "Large Urban Areas",
            "ruc21_id": "1",
            "ttwa": "Aberdeen",
            "ttwa_id": "S22000047",
          },
          {
            "admin_county": null,
            "admin_county_id": null,
            "admin_district": "Aberdeen City",
            "admin_district_id": "S12000033",
            "admin_ward": "George St/Harbour",
            "admin_ward_id": "S13002842",
            "bua": null,
            "bua_id": null,
            "cancer_alliance": null,
            "cancer_alliance_id": null,
            "ccg": "Aberdeen City Community Health Partnership",
            "ccg_code": "012",
            "ccg_id": "S03000012",
            "ced": null,
            "ced_id": null,
            "constituency_id": "S14000061",
            "country": "Scotland",
            "date_of_introduction": "199606",
            "date_of_termination": null,
            "distance": 0,
            "eastings": 394235,
            "european_electoral_region": "Scotland",
            "icb": null,
            "icb_id": null,
            "incode": "1AX",
            "index_of_multiple_deprivation": 3888,
            "latitude": 57.14959,
            "lep1": null,
            "lep1_id": null,
            "lep2": null,
            "lep2_id": null,
            "longitude": -2.096923,
            "lsoa": "George Street - 02",
            "lsoa11": "George Street - 02",
            "lsoa11_id": "S01006646",
            "lsoa21": "George Street - 02",
            "lsoa21_id": "S01013627",
            "lsoa_id": "S01013627",
            "msoa": "George Street",
            "msoa11": "George Street",
            "msoa11_id": "S02001261",
            "msoa21": "George Street",
            "msoa21_id": "S02002541",
            "msoa_id": "S02002541",
            "national_park": null,
            "national_park_id": null,
            "nhs_ha": "Grampian",
            "nhs_region": null,
            "nhs_region_id": null,
            "northings": 806529,
            "nuts": "Aberdeen City",
            "nuts_code": "TLM50",
            "nuts_id": "S30000026",
            "oa21_id": "S00136377",
            "outcode": "AB10",
            "parish": null,
            "parish_id": null,
            "parliamentary_constituency": "Aberdeen South",
            "pc_compact": "AB101AX",
            "pfa": "Scotland",
            "pfa_id": "S23000009",
            "postcode": "AB10 1AX",
            "primary_care_trust": "Aberdeen City Community Health Partnership",
            "quality": 1,
            "region": null,
            "ruc11": "(Scotland) Large Urban Area",
            "ruc11_id": "1",
            "ruc21": "Large Urban Areas",
            "ruc21_id": "1",
            "ttwa": "Aberdeen",
            "ttwa_id": "S22000047",
          },
        ]
      `);
    });
    it("returns null when nothing is within the radius", async () => {
      expect(
        await nearestPostcodes({
          longitude: "-30",
          latitude: "50",
          radius: "100",
        })
      ).toMatchInlineSnapshot(`null`);
    });
    it("clamps radius above MAX to MAX", async () => {
      const rows = await nearestPostcodes({
        ...ANCHOR,
        radius: "999999",
        limit: "1",
      });
      expect({
        length: rows?.length ?? null,
        first: rows?.[0]?.postcode ?? null,
      }).toMatchInlineSnapshot(`
        {
          "first": "AB10 1AB",
          "length": 1,
        }
      `);
    });
    it("rejects non-numeric longitude", async () => {
      await expect(
        nearestPostcodes({ longitude: "x", latitude: "0" })
      ).rejects.toThrowErrorMatchingInlineSnapshot(`[PostcodesioHttpError: PostcodesIO HTTP Error: 400 Invalid longitude/latitude submitted]`);
    });
  });

  describe("nearestPostcodesMany()", () => {
    it("returns one grouped array per input, preserving order", async () => {
      expect(
        await nearestPostcodesMany([
          { longitude: -2.096923, latitude: 57.14959, radius: 500, limit: 3 },
          { longitude: -2.097, latitude: 57.148, radius: 500, limit: 2 },
        ])
      ).toMatchInlineSnapshot(`
        [
          [
            {
              "admin_county": null,
              "admin_county_id": null,
              "admin_district": "Aberdeen City",
              "admin_district_id": "S12000033",
              "admin_ward": "George St/Harbour",
              "admin_ward_id": "S13002842",
              "bua": null,
              "bua_id": null,
              "cancer_alliance": null,
              "cancer_alliance_id": null,
              "ccg": "Aberdeen City Community Health Partnership",
              "ccg_code": "012",
              "ccg_id": "S03000012",
              "ced": null,
              "ced_id": null,
              "constituency_id": "S14000061",
              "country": "Scotland",
              "date_of_introduction": "201106",
              "date_of_termination": null,
              "distance": 0,
              "eastings": 394235,
              "european_electoral_region": "Scotland",
              "icb": null,
              "icb_id": null,
              "idx": 0,
              "incode": "1AB",
              "index_of_multiple_deprivation": 3888,
              "latitude": 57.14959,
              "lep1": null,
              "lep1_id": null,
              "lep2": null,
              "lep2_id": null,
              "longitude": -2.096923,
              "lsoa": "George Street - 02",
              "lsoa11": "George Street - 02",
              "lsoa11_id": "S01006646",
              "lsoa21": "George Street - 02",
              "lsoa21_id": "S01013627",
              "lsoa_id": "S01013627",
              "msoa": "George Street",
              "msoa11": "George Street",
              "msoa11_id": "S02001261",
              "msoa21": "George Street",
              "msoa21_id": "S02002541",
              "msoa_id": "S02002541",
              "national_park": null,
              "national_park_id": null,
              "nhs_ha": "Grampian",
              "nhs_region": null,
              "nhs_region_id": null,
              "northings": 806529,
              "nuts": "Aberdeen City",
              "nuts_code": "TLM50",
              "nuts_id": "S30000026",
              "oa21_id": "S00136377",
              "outcode": "AB10",
              "parish": null,
              "parish_id": null,
              "parliamentary_constituency": "Aberdeen South",
              "pc_compact": "AB101AB",
              "pfa": "Scotland",
              "pfa_id": "S23000009",
              "postcode": "AB10 1AB",
              "primary_care_trust": "Aberdeen City Community Health Partnership",
              "quality": 1,
              "region": null,
              "ruc11": "(Scotland) Large Urban Area",
              "ruc11_id": "1",
              "ruc21": "Large Urban Areas",
              "ruc21_id": "1",
              "ttwa": "Aberdeen",
              "ttwa_id": "S22000047",
            },
            {
              "admin_county": null,
              "admin_county_id": null,
              "admin_district": "Aberdeen City",
              "admin_district_id": "S12000033",
              "admin_ward": "George St/Harbour",
              "admin_ward_id": "S13002842",
              "bua": null,
              "bua_id": null,
              "cancer_alliance": null,
              "cancer_alliance_id": null,
              "ccg": "Aberdeen City Community Health Partnership",
              "ccg_code": "012",
              "ccg_id": "S03000012",
              "ced": null,
              "ced_id": null,
              "constituency_id": "S14000061",
              "country": "Scotland",
              "date_of_introduction": "199606",
              "date_of_termination": null,
              "distance": 0,
              "eastings": 394235,
              "european_electoral_region": "Scotland",
              "icb": null,
              "icb_id": null,
              "idx": 0,
              "incode": "1AF",
              "index_of_multiple_deprivation": 3888,
              "latitude": 57.14959,
              "lep1": null,
              "lep1_id": null,
              "lep2": null,
              "lep2_id": null,
              "longitude": -2.096923,
              "lsoa": "George Street - 02",
              "lsoa11": "George Street - 02",
              "lsoa11_id": "S01006646",
              "lsoa21": "George Street - 02",
              "lsoa21_id": "S01013627",
              "lsoa_id": "S01013627",
              "msoa": "George Street",
              "msoa11": "George Street",
              "msoa11_id": "S02001261",
              "msoa21": "George Street",
              "msoa21_id": "S02002541",
              "msoa_id": "S02002541",
              "national_park": null,
              "national_park_id": null,
              "nhs_ha": "Grampian",
              "nhs_region": null,
              "nhs_region_id": null,
              "northings": 806529,
              "nuts": "Aberdeen City",
              "nuts_code": "TLM50",
              "nuts_id": "S30000026",
              "oa21_id": "S00136377",
              "outcode": "AB10",
              "parish": null,
              "parish_id": null,
              "parliamentary_constituency": "Aberdeen South",
              "pc_compact": "AB101AF",
              "pfa": "Scotland",
              "pfa_id": "S23000009",
              "postcode": "AB10 1AF",
              "primary_care_trust": "Aberdeen City Community Health Partnership",
              "quality": 1,
              "region": null,
              "ruc11": "(Scotland) Large Urban Area",
              "ruc11_id": "1",
              "ruc21": "Large Urban Areas",
              "ruc21_id": "1",
              "ttwa": "Aberdeen",
              "ttwa_id": "S22000047",
            },
            {
              "admin_county": null,
              "admin_county_id": null,
              "admin_district": "Aberdeen City",
              "admin_district_id": "S12000033",
              "admin_ward": "George St/Harbour",
              "admin_ward_id": "S13002842",
              "bua": null,
              "bua_id": null,
              "cancer_alliance": null,
              "cancer_alliance_id": null,
              "ccg": "Aberdeen City Community Health Partnership",
              "ccg_code": "012",
              "ccg_id": "S03000012",
              "ced": null,
              "ced_id": null,
              "constituency_id": "S14000061",
              "country": "Scotland",
              "date_of_introduction": "199606",
              "date_of_termination": null,
              "distance": 0,
              "eastings": 394235,
              "european_electoral_region": "Scotland",
              "icb": null,
              "icb_id": null,
              "idx": 0,
              "incode": "1AH",
              "index_of_multiple_deprivation": 3888,
              "latitude": 57.14959,
              "lep1": null,
              "lep1_id": null,
              "lep2": null,
              "lep2_id": null,
              "longitude": -2.096923,
              "lsoa": "George Street - 02",
              "lsoa11": "George Street - 02",
              "lsoa11_id": "S01006646",
              "lsoa21": "George Street - 02",
              "lsoa21_id": "S01013627",
              "lsoa_id": "S01013627",
              "msoa": "George Street",
              "msoa11": "George Street",
              "msoa11_id": "S02001261",
              "msoa21": "George Street",
              "msoa21_id": "S02002541",
              "msoa_id": "S02002541",
              "national_park": null,
              "national_park_id": null,
              "nhs_ha": "Grampian",
              "nhs_region": null,
              "nhs_region_id": null,
              "northings": 806529,
              "nuts": "Aberdeen City",
              "nuts_code": "TLM50",
              "nuts_id": "S30000026",
              "oa21_id": "S00136377",
              "outcode": "AB10",
              "parish": null,
              "parish_id": null,
              "parliamentary_constituency": "Aberdeen South",
              "pc_compact": "AB101AH",
              "pfa": "Scotland",
              "pfa_id": "S23000009",
              "postcode": "AB10 1AH",
              "primary_care_trust": "Aberdeen City Community Health Partnership",
              "quality": 1,
              "region": null,
              "ruc11": "(Scotland) Large Urban Area",
              "ruc11_id": "1",
              "ruc21": "Large Urban Areas",
              "ruc21_id": "1",
              "ttwa": "Aberdeen",
              "ttwa_id": "S22000047",
            },
          ],
          [
            {
              "admin_county": null,
              "admin_county_id": null,
              "admin_district": "Aberdeen City",
              "admin_district_id": "S12000033",
              "admin_ward": "George St/Harbour",
              "admin_ward_id": "S13002842",
              "bua": null,
              "bua_id": null,
              "cancer_alliance": null,
              "cancer_alliance_id": null,
              "ccg": "Aberdeen City Community Health Partnership",
              "ccg_code": "012",
              "ccg_id": "S03000012",
              "ced": null,
              "ced_id": null,
              "constituency_id": "S14000061",
              "country": "Scotland",
              "date_of_introduction": "200702",
              "date_of_termination": null,
              "distance": 31.85453006,
              "eastings": 394251,
              "european_electoral_region": "Scotland",
              "icb": null,
              "icb_id": null,
              "idx": 1,
              "incode": "9SD",
              "index_of_multiple_deprivation": 3888,
              "latitude": 57.148216,
              "lep1": null,
              "lep1_id": null,
              "lep2": null,
              "lep2_id": null,
              "longitude": -2.096655,
              "lsoa": "George Street - 02",
              "lsoa11": "George Street - 02",
              "lsoa11_id": "S01006646",
              "lsoa21": "George Street - 02",
              "lsoa21_id": "S01013627",
              "lsoa_id": "S01013627",
              "msoa": "George Street",
              "msoa11": "George Street",
              "msoa11_id": "S02001261",
              "msoa21": "George Street",
              "msoa21_id": "S02002541",
              "msoa_id": "S02002541",
              "national_park": null,
              "national_park_id": null,
              "nhs_ha": "Grampian",
              "nhs_region": null,
              "nhs_region_id": null,
              "northings": 806376,
              "nuts": "Aberdeen City",
              "nuts_code": "TLM50",
              "nuts_id": "S30000026",
              "oa21_id": "S00136377",
              "outcode": "AB12",
              "parish": null,
              "parish_id": null,
              "parliamentary_constituency": "Aberdeen South",
              "pc_compact": "AB129SD",
              "pfa": "Scotland",
              "pfa_id": "S23000009",
              "postcode": "AB12 9SD",
              "primary_care_trust": "Aberdeen City Community Health Partnership",
              "quality": 1,
              "region": null,
              "ruc11": "(Scotland) Large Urban Area",
              "ruc11_id": "1",
              "ruc21": "Large Urban Areas",
              "ruc21_id": "1",
              "ttwa": "Aberdeen",
              "ttwa_id": "S22000047",
            },
            {
              "admin_county": null,
              "admin_county_id": null,
              "admin_district": "Aberdeen City",
              "admin_district_id": "S12000033",
              "admin_ward": "George St/Harbour",
              "admin_ward_id": "S13002842",
              "bua": null,
              "bua_id": null,
              "cancer_alliance": null,
              "cancer_alliance_id": null,
              "ccg": "Aberdeen City Community Health Partnership",
              "ccg_code": "012",
              "ccg_id": "S03000012",
              "ced": null,
              "ced_id": null,
              "constituency_id": "S14000061",
              "country": "Scotland",
              "date_of_introduction": "199606",
              "date_of_termination": null,
              "distance": 46.03985247,
              "eastings": 394198,
              "european_electoral_region": "Scotland",
              "icb": null,
              "icb_id": null,
              "idx": 1,
              "incode": "1AS",
              "index_of_multiple_deprivation": 3888,
              "latitude": 57.148296,
              "lep1": null,
              "lep1_id": null,
              "lep2": null,
              "lep2_id": null,
              "longitude": -2.097531,
              "lsoa": "George Street - 02",
              "lsoa11": "George Street - 02",
              "lsoa11_id": "S01006646",
              "lsoa21": "George Street - 02",
              "lsoa21_id": "S01013627",
              "lsoa_id": "S01013627",
              "msoa": "George Street",
              "msoa11": "George Street",
              "msoa11_id": "S02001261",
              "msoa21": "George Street",
              "msoa21_id": "S02002541",
              "msoa_id": "S02002541",
              "national_park": null,
              "national_park_id": null,
              "nhs_ha": "Grampian",
              "nhs_region": null,
              "nhs_region_id": null,
              "northings": 806385,
              "nuts": "Aberdeen City",
              "nuts_code": "TLM50",
              "nuts_id": "S30000026",
              "oa21_id": "S00136377",
              "outcode": "AB10",
              "parish": null,
              "parish_id": null,
              "parliamentary_constituency": "Aberdeen South",
              "pc_compact": "AB101AS",
              "pfa": "Scotland",
              "pfa_id": "S23000009",
              "postcode": "AB10 1AS",
              "primary_care_trust": "Aberdeen City Community Health Partnership",
              "quality": 1,
              "region": null,
              "ruc11": "(Scotland) Large Urban Area",
              "ruc11_id": "1",
              "ruc21": "Large Urban Areas",
              "ruc21_id": "1",
              "ttwa": "Aberdeen",
              "ttwa_id": "S22000047",
            },
          ],
        ]
      `);
    });
    it("returns empty array for empty input", async () => {
      expect(await nearestPostcodesMany([])).toMatchInlineSnapshot(`[]`);
    });
    it("returns empty inner arrays for inputs with no nearby postcodes", async () => {
      expect(
        await nearestPostcodesMany([
          { longitude: -30, latitude: 50, radius: 100, limit: 5 },
        ])
      ).toMatchInlineSnapshot(`
        [
          [],
        ]
      `);
    });
  });

  describe("random()", () => {
    it("returns a row shaped like a live postcode", async () => {
      const originalRandom = Math.random;
      Math.random = () => 0.5;
      try {
        const row = await random();
        expect({
          isObject: row !== null && typeof row === "object",
          hasPostcode: typeof row?.postcode === "string",
        }).toMatchInlineSnapshot(`
          {
            "hasPostcode": true,
            "isObject": true,
          }
        `);
      } finally {
        Math.random = originalRandom;
      }
    });
  });
});
