// Contract tests for api/app/queries/scottish_postcodes.ts.
// Re-capture with `pnpm vitest run test/queries.scottish_postcodes.integration.ts -u`.

import { describe, expect, it } from "vitest";
import { find } from "../api/app/queries/scottish_postcodes";

const KNOWN_SCOTTISH = "AB10 1AB";

describe("queries/scottish_postcodes (contract)", () => {
  describe("find()", () => {
    it("returns the row for a known Scottish postcode", async () => {
      expect(await find(KNOWN_SCOTTISH)).toMatchInlineSnapshot(`
        {
          "census_household_count": null,
          "census_household_count_1991": null,
          "census_household_count_2001": null,
          "census_household_count_2011": null,
          "census_population_count": null,
          "census_population_count_1991": null,
          "census_population_count_2001": null,
          "census_population_count_2011": null,
          "civil_parish": "Aberdeen",
          "civil_parish_code": "S35000005",
          "council_area": "Aberdeen City",
          "council_area_code": "S12000033",
          "data_zone": "George Street - 02",
          "data_zone_2001": "S01000125",
          "data_zone_2001_code": "S01000125",
          "data_zone_2011": "S01006646",
          "data_zone_2011_code": "S01006646",
          "data_zone_code": "S01013627",
          "date_of_deletion": null,
          "date_of_introduction": "11/7/2011 00:00:00",
          "eastings": 394235,
          "electoral_ward": "George St/Harbour",
          "electoral_ward_code": "S13002842",
          "enterprise_region": "Aberdeen City and Shire",
          "enterprise_region_code": "S09000001",
          "grid_link_indicator": "Y",
          "grid_link_positional_accuracy": "1",
          "health_board_area": "Grampian",
          "health_board_area_1995": "Grampian",
          "health_board_area_1995_code": "02",
          "health_board_area_2006": "Grampian",
          "health_board_area_2006_code": "S08000006",
          "health_board_area_code": "S08000020",
          "incode": "1AB",
          "integration_authority": "Aberdeen City",
          "integration_authority_code": "S37000001",
          "intermediate_zone": "George Street",
          "intermediate_zone_2001": "S02000024",
          "intermediate_zone_2001_code": "S02000024",
          "intermediate_zone_2011": "S02001261",
          "intermediate_zone_2011_code": "S02001261",
          "intermediate_zone_code": "S02002541",
          "island": "Mainland of Scotland",
          "island_code": "000",
          "itl_level_2": "North Eastern Scotland",
          "itl_level_2_code": "TLM5",
          "itl_level_3": "Aberdeen City and Aberdeenshire",
          "itl_level_3_code": "TLM50",
          "latitude": 57.14958998,
          "lau_level_1": "Aberdeen City",
          "lau_level_1_code": "S30000026",
          "linked_small_user_postcode": "AB10 1FF",
          "local_government_district": "Aberdeen City",
          "local_government_district_1991": "Aberdeen City",
          "local_government_district_1991_code": "15",
          "local_government_district_code": "15",
          "locality": "Aberdeen",
          "locality_1991": "Aberdeen",
          "locality_2001": "Aberdeen",
          "locality_2020": "Aberdeen",
          "locality_code": "S52000002",
          "longitude": -2.09692315,
          "national_park": null,
          "national_park_code": null,
          "never_digitised": null,
          "northings": 806529,
          "outcode": "AB10",
          "output_area": "S00136377",
          "output_area_1991": "6015AA21B",
          "output_area_2001": "S00000036",
          "output_area_2011": "S00090540",
          "pc_compact": "AB101AB",
          "postcode": "AB10 1AB",
          "postcode_district": "AB10",
          "postcode_sector": "AB10 1",
          "registration_district": "S12000033",
          "registration_district_code": "S12000033",
          "roa_community_planning_partnership": null,
          "roa_community_planning_partnership_code": null,
          "roa_local": null,
          "roa_local_code": null,
          "scottish_index_of_multiple_deprivation": 3888,
          "scottish_parliamentary_constituency": "Aberdeen Central",
          "scottish_parliamentary_constituency_code": "S16000074",
          "scottish_parliamentary_region": "North East Scotland",
          "scottish_parliamentary_region_code": "S17000014",
          "settlement": "Aberdeen, Milltimber, and Peterculter",
          "settlement_2001": "Aberdeen",
          "settlement_2020": null,
          "settlement_code": "S53000002",
          "split_indicator": "N",
          "strategic_development_planning_area": "S11000001",
          "strategic_development_planning_area_code": "S11000001",
          "travel_to_work_area": "Aberdeen",
          "travel_to_work_area_code": "S22000047",
          "uk_parliamentary_constituency": "Aberdeen South",
          "uk_parliamentary_constituency_code": "S14000061",
          "urban_rural_6_fold": "1",
          "urban_rural_8_fold": "1",
          "user_type": "large",
        }
      `);
    });
    it("normalises whitespace and case", async () => {
      expect(await find("  ab10 1ab  ")).toMatchInlineSnapshot(`
        {
          "census_household_count": null,
          "census_household_count_1991": null,
          "census_household_count_2001": null,
          "census_household_count_2011": null,
          "census_population_count": null,
          "census_population_count_1991": null,
          "census_population_count_2001": null,
          "census_population_count_2011": null,
          "civil_parish": "Aberdeen",
          "civil_parish_code": "S35000005",
          "council_area": "Aberdeen City",
          "council_area_code": "S12000033",
          "data_zone": "George Street - 02",
          "data_zone_2001": "S01000125",
          "data_zone_2001_code": "S01000125",
          "data_zone_2011": "S01006646",
          "data_zone_2011_code": "S01006646",
          "data_zone_code": "S01013627",
          "date_of_deletion": null,
          "date_of_introduction": "11/7/2011 00:00:00",
          "eastings": 394235,
          "electoral_ward": "George St/Harbour",
          "electoral_ward_code": "S13002842",
          "enterprise_region": "Aberdeen City and Shire",
          "enterprise_region_code": "S09000001",
          "grid_link_indicator": "Y",
          "grid_link_positional_accuracy": "1",
          "health_board_area": "Grampian",
          "health_board_area_1995": "Grampian",
          "health_board_area_1995_code": "02",
          "health_board_area_2006": "Grampian",
          "health_board_area_2006_code": "S08000006",
          "health_board_area_code": "S08000020",
          "incode": "1AB",
          "integration_authority": "Aberdeen City",
          "integration_authority_code": "S37000001",
          "intermediate_zone": "George Street",
          "intermediate_zone_2001": "S02000024",
          "intermediate_zone_2001_code": "S02000024",
          "intermediate_zone_2011": "S02001261",
          "intermediate_zone_2011_code": "S02001261",
          "intermediate_zone_code": "S02002541",
          "island": "Mainland of Scotland",
          "island_code": "000",
          "itl_level_2": "North Eastern Scotland",
          "itl_level_2_code": "TLM5",
          "itl_level_3": "Aberdeen City and Aberdeenshire",
          "itl_level_3_code": "TLM50",
          "latitude": 57.14958998,
          "lau_level_1": "Aberdeen City",
          "lau_level_1_code": "S30000026",
          "linked_small_user_postcode": "AB10 1FF",
          "local_government_district": "Aberdeen City",
          "local_government_district_1991": "Aberdeen City",
          "local_government_district_1991_code": "15",
          "local_government_district_code": "15",
          "locality": "Aberdeen",
          "locality_1991": "Aberdeen",
          "locality_2001": "Aberdeen",
          "locality_2020": "Aberdeen",
          "locality_code": "S52000002",
          "longitude": -2.09692315,
          "national_park": null,
          "national_park_code": null,
          "never_digitised": null,
          "northings": 806529,
          "outcode": "AB10",
          "output_area": "S00136377",
          "output_area_1991": "6015AA21B",
          "output_area_2001": "S00000036",
          "output_area_2011": "S00090540",
          "pc_compact": "AB101AB",
          "postcode": "AB10 1AB",
          "postcode_district": "AB10",
          "postcode_sector": "AB10 1",
          "registration_district": "S12000033",
          "registration_district_code": "S12000033",
          "roa_community_planning_partnership": null,
          "roa_community_planning_partnership_code": null,
          "roa_local": null,
          "roa_local_code": null,
          "scottish_index_of_multiple_deprivation": 3888,
          "scottish_parliamentary_constituency": "Aberdeen Central",
          "scottish_parliamentary_constituency_code": "S16000074",
          "scottish_parliamentary_region": "North East Scotland",
          "scottish_parliamentary_region_code": "S17000014",
          "settlement": "Aberdeen, Milltimber, and Peterculter",
          "settlement_2001": "Aberdeen",
          "settlement_2020": null,
          "settlement_code": "S53000002",
          "split_indicator": "N",
          "strategic_development_planning_area": "S11000001",
          "strategic_development_planning_area_code": "S11000001",
          "travel_to_work_area": "Aberdeen",
          "travel_to_work_area_code": "S22000047",
          "uk_parliamentary_constituency": "Aberdeen South",
          "uk_parliamentary_constituency_code": "S14000061",
          "urban_rural_6_fold": "1",
          "urban_rural_8_fold": "1",
          "user_type": "large",
        }
      `);
    });
    it("returns null for a syntactically invalid postcode", async () => {
      expect(await find("NOT A POSTCODE")).toMatchInlineSnapshot(`null`);
    });
    it("returns null for a valid but unknown postcode", async () => {
      expect(await find("ZZ99 9ZZ")).toMatchInlineSnapshot(`null`);
    });
    it("returns null for nullish input", async () => {
      expect(await find(null)).toMatchInlineSnapshot(`null`);
      expect(await find(undefined)).toMatchInlineSnapshot(`null`);
      expect(await find("")).toMatchInlineSnapshot(`null`);
    });
  });
});
