FROM postgis/postgis:17-3.5

COPY latest /tmp/latest
COPY docker/postgresql.conf /etc/postgresql/postgresql.conf
COPY docker/prewarm.sql /docker-entrypoint-initdb.d/02-prewarm.sql

RUN mkdir -p /docker-entrypoint-initdb.d/ && \
    apt-get update && apt-get install -y curl && \
    curl -o /docker-entrypoint-initdb.d/01-postcodesiodata.sql.gz $(cat /tmp/latest) && \
    rm -rf /var/lib/apt/lists/*

CMD ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]
